version: "3"
services:
  jetstream-poc:
    build:
      args:
        PORT: '80'
      context: .
    container_name: jetstream-poc
    volumes:
      - .:/var/www/html
    ports:
      - 86:80
    networks:
      default:
        ipv4_address: 183.12.0.1
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - jetstream-poc-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jetstream-poc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - 5436:5432
    networks:
      default:
        ipv4_address: 183.12.0.2
volumes:
  jetstream-poc-db-data: {}
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 183.12.0.0/10
